# Generated by Django 5.2.5 on 2025-08-15 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_remove_order_paymentid_order_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
