# Generated by Django 5.2.5 on 2025-08-29 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_medicine_unit_quantity_lowstockalert_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransaction',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='stocktransaction',
            name='medicine',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='unit_quantity',
        ),
        migrations.DeleteModel(
            name='LowStockAlert',
        ),
        migrations.DeleteModel(
            name='StockTransaction',
        ),
    ]
