# Generated by Django 5.2.5 on 2025-08-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ChatApp', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
